language: node_js
node_js:
  - "6.1"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
  - npm install
script:
  - npm run build && gulp s3-deploy
branches:
  only:
    - source
